version: "3.8"
services:
  keg-components:
    privileged: true
    build:
      context: ${KEG_CONTEXT_PATH}
      dockerfile: ${KEG_DOCKER_FILE}
      args:
        - GIT_COMPONENTS_URL
        - DOC_APP_PATH
        - KEG_IMAGE_FROM
        - KEG_NODE_VERSION
        - PUBLIC_GIT_KEY
    environment:
      - CHOKIDAR_USEPOLLING
      - DOC_APP_PATH
      - DOC_CLI_PATH
      - DOC_COMPONENTS_PATH
      - DOC_RETHEME_PATH
      - DOC_JSUTILS_PATH
      - GIT_CLI_URL
      - GIT_COMPONENTS_URL
      - GIT_RETHEME_URL
      - KEG_EXEC_CMD
      - KEG_DOCKER_EXEC
      - KEG_NM_INSTALL
      - NODE_ENV
      - PUBLIC_GIT_KEY

