version: "3.8"
services:
  retheme:
    image: ${IMAGE}
    tty: true
    stdin_open: true
    privileged: true
    volumes:
      - ${CLI_PATH}:${DOC_CLI_PATH}
    build:
      context: ${KEG_CONTEXT_PATH}
      dockerfile: ${KEG_DOCKER_FILE}
      args:
        - DOC_APP_PATH
        - DOC_APP_PORT
        - ENV
        - NODE_ENV
    container_name: ${CONTAINER_NAME}
    environment:
      - DOC_APP_PATH
      - DOC_APP_PORT
      - ENV
      - KEG_EXEC_CMD
      - KEG_DOCKER_EXEC
      - KEG_NM_INSTALL
      - NODE_ENV
    ports:
      - 80:${DOC_APP_PORT}
      - ${DOC_APP_PORT}:${DOC_APP_PORT}
