
env:
  # --- LOCAL ENV CONTEXT --- #
  COMPONENTS_PATH: "{{ cli.paths.components }}/build"
  RETHEME_PATH: "{{ cli.paths.retheme }}/build"
  RESOLVER_PATH: "{{ cli.paths.resolver }}/src"

  # --- TAP ENV CONTEXT --- #

  # Docker / Docker Compose paths
  CONTEXT_DOCKER_FILE: "{{ cli.paths.containers }}/tap/Dockerfile"
  CONTEXT_VALUES_FILE: "{{ cli.paths.containers }}/tap/values.yml"
  COMPOSE_DEFAULT: "{{ cli.paths.containers }}/tap/compose-default.yml"
  COMPOSE_SYNC: "{{ cli.paths.containers }}/tap/compose-sync.yml"

  # The CONTEXT_PATH env should be the location of the tap being run
  # So it should NOT be set inside the .env file
  CONTEXT_PATH: INITIAL

  # --- DOCKER ENV CONTEXT --- #

  # Default location of the tap in the docker container
  DOC_APP_PATH: /keg/tap
  DOC_APP_PORT: 19006
  DOC_CORE_PATH: /keg/tap/node_modules/keg-core
  DOC_COMPONENTS_PATH: /keg/tap/node_modules/keg-core/node_modules/@simpleviewinc/keg-components/build
  DOC_RETHEME_PATH: /keg/tap/node_modules/keg-core/node_modules/@simpleviewinc/re-theme/build
  DOC_RESOLVER_PATH: /keg/tap/node_modules/keg-core/node_modules/@simpleviewinc/tap-resolver/src
  NM_CACHE: /keg/nm-cache/tap


  # --- GENERAL CONTEXT ENVs --- #

  # Image Build information
  IMAGE: tap
  VERSION: "0.0.1"
  CONTAINER_NAME: tap

  # Git tap url in github
  GIT_TAP_URL: INITIAL
