name: Publish

# events but only for the master branch
on:
  push:
    branches: [master]

jobs:

  build_and_deploy_package:
    runs-on: ubuntu-latest
    steps:
      
    # Checks-out the repo on branch master (default) under $GITHUB_WORKSPACE
    - uses: actions/checkout@v2

    - name: Setup and publish
      env:
        GIT_KEY: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd $GITHUB_WORKSPACE
        yarn publish

