
start: /bin/bash /keg/keg-cli/containers/core/run.sh
env:
  # --- LOCAL ENV CONTEXT --- #
  COMPONENTS_PATH: "{{ cli.paths.components }}"
  RETHEME_PATH: "{{ cli.taps.links.retheme }}"
  RESOLVER_PATH: "{{ cli.paths.resolver }}"

  # --- CORE ENV CONTEXT --- #

  # Docker data
  KEG_CONTEXT_PATH: "{{ cli.paths.core }}"
  KEG_DOCKER_FILE: "{{ cli.paths.containers }}/core/Dockerfile"
  KEG_VALUES_FILE: "{{ cli.paths.containers }}/core/values.yml"
  KEG_MUTAGEN_PATH: "{{ cli.paths.containers }}/core/mutagen.yml"

  # The default docker-compose file path
  KEG_COMPOSE_DEFAULT: "{{ cli.paths.containers }}/core/docker-compose.yml"
  # Can also define other an override compose files
  # Other compose files can loaded by setting an ENVS as follows:
    # KEG_COMPOSE_REPO="/path/to/override.yml"
    # KEG_COMPOSE_CORE_<ENV>: "/path/to/override.yml"
    # KEG_COMPOSE_<ENV>: "/path/to/override.yml"

  KEG_EXEC_CMD: tap:start

  # --- DOCKER ENV CONTEXT --- #

  DOC_APP_PATH: "/keg/keg-core"

  # Port the application will use when running within the container
  # Required to allow the keg-proxy to route traffic to it

  # Defines the location in a docker container for a dependency
  # This allows mutagen to know where to sync the local version of the dependency
  DOC_CORE_PATH: "/keg/keg-core"
  DOC_COMPONENTS_PATH: "/keg/keg-core/node_modules/@keg-hub/keg-components"
  DOC_JSUTILS_PATH: "/keg/keg-core/node_modules/@keg-hub/jsutils"
  DOC_RETHEME_PATH: "/keg/keg-core/node_modules/@keg-hub/re-theme"
  DOC_RESOLVER_PATH: "/keg/keg-core/node_modules/@keg-hub/tap-resolver"

  # --- KEG-PROXY ENVs --- #

  # To override the host header used by the proxy to route traffic to this container
  # add KEG_PROXY_HOST env and set it's value to the what the host header should be
  # the default is <container-context>-<image-tag>.local.kegdev.xyz
    # KEG_PROXY_HOST: core.local.kegdev.xyz

  # KEG_DOCKER_NETWORK: custom-docker-network
    # To override the default docker network used by the proxy to route traffic to this container
    # add KEG_PROXY_HOST env and set it's value to the what network should be used
    # the default is 'keg-hub-net'

  # Port the application will use when running within the container
  # Required to allow the keg-proxy to route traffic to it
  KEG_PROXY_PORT: 19006

  # --- GENERAL CONTEXT ENVs --- #

  # Image Build information
  IMAGE: "keg-core"
  VERSION: "0.0.1"
  CONTAINER_NAME: "keg-core"
  CHOKIDAR_USEPOLLING: 1
